// <auto-generated />
namespace CinemaTickets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTableHallsRowsPlaces : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableHallsRowsPlaces));
        
        string IMigrationMetadata.Id
        {
            get { return "202107281818241_addTableHallsRowsPlaces"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
